/*
Copyright (c) 2025 Jared Nishikawa

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

package sgfsamples

const (
	Empty             = "(;PW[White]RU[Japanese]KM[6.5]GM[1]FF[4]CA[UTF-8]SZ[19]PB[Black])"
	SimpleTwoBranches = "(;PW[White]RU[Japanese]KM[6.5]GM[1]FF[4]CA[UTF-8]SZ[19]PB[Black](;B[pd];W[dd];B[pp];W[dp])(;B[dd];W[ee]))"
	SimpleWithComment = "(;PW[White]RU[Japanese]KM[6.5]GM[1]FF[4]CA[UTF-8]SZ[19]PB[Black]C[comment1](;B[pd];W[dd];B[pp];W[dp])(;B[dd];W[ee]))"
	SimpleFourMoves   = "(;PW[White]RU[Japanese]KM[6.5]GM[1]FF[4]CA[UTF-8]SZ[19]PB[Black];B[pd];W[dd];B[pp];W[dp];B[];W[])"
	SimpleEightMoves  = "(;PW[White]RU[Japanese]KM[6.5]GM[1]FF[4]CA[UTF-8]SZ[19]PB[Black];B[pd];W[dd];B[pp];W[dp];B[cc];W[dc];B[cd];W[de])"
	Scoring1          = "(;SZ[19]KM[6.5]FF[4]WRE[B+11.5]OT[3x30 byo-yomi]PB[black]PW[white]GM[1]DT[2025-09-14]TM[2400]RU[Japanese]CA[UTF-8];B[pd];W[dd];B[pp];W[dp];B[fq];W[qc];B[qd];W[pc];B[od];W[nb];B[dn];W[en];B[em];W[fn];B[cq];W[dm];B[dq];W[cn];B[cf];W[fc];B[cd];W[cc];B[bc];W[ce];B[bd];W[be];B[de];W[bf];B[dc];W[ed];B[db];W[cg];B[dl];W[cm];B[pj];W[ep];B[gq];W[mc];B[md];W[ld];B[nc];W[lb];B[le];W[ke];B[nd];W[rc];B[kf];W[kd];B[jf];W[lf];B[me];W[lg];B[kh];W[pi];B[oi];W[qj];B[ph];W[qi];B[oj];W[ql];B[df];W[dh];B[ff];W[hd];B[dg];W[ch];B[hf];W[gg];B[he];W[gd];B[fe];W[lj];B[lh];W[qh];B[dj];W[ei];B[fk];W[gj];B[gk];W[hj];B[hk];W[ej];B[cl];W[ek];B[el];W[gm];B[gl];W[ij];B[ik];W[im];B[jl];W[jk];B[il];W[jn];B[bi];W[bh];B[bk];W[kk];B[hn];W[hm];B[kl];W[ll];B[km];W[hq];B[cp];W[co];B[ji];W[jj];B[lm];W[ml];B[hp];W[eq];B[er];W[fr];B[gr];W[ip];B[io];W[gp];B[ho];W[dr];B[fs];W[cr];B[br];W[bq];B[bp];W[ar];B[aq];W[bs];B[as];W[jo];B[iq];W[ar];B[fj];W[fi];B[as];W[lo];B[mm];W[ar];B[ob];W[oc];B[as];W[nm];B[bm];W[no];B[nn];W[mn];B[on];W[oo];B[po];W[pn];B[om];W[nl];B[ol];W[nq];B[jp];W[kp];B[oq];W[nr];B[np];W[mp];B[op];W[mo];B[or];W[an];B[gi];W[hh];B[am];W[bn];B[dk];W[ar];B[fm];W[gn];B[as];W[aj];B[bj];W[ar];B[je];W[bq];B[fh];W[gh];B[br];W[fg];B[as];W[pm];B[pl];W[qm];B[oh];W[lq];B[ic];W[jb];B[jc];W[kc];B[ib];W[ia];B[ha];W[ja];B[hb];W[rp];B[ro];W[qo];B[rq];W[rn];B[qp];W[so];B[qr];W[ar];B[na];W[mb];B[as];W[bb];B[ab];W[ar];B[kb];W[ka];B[as];W[cb];B[ca];W[ar];B[la];W[ma];B[as];W[ai];B[ak];W[ar];B[qk];W[rk];B[as];W[bl];B[al];W[ar];B[kn];W[ko];B[as];W[jd];B[id];W[ar];B[mk];W[lk];B[as];W[ad];B[ba];W[ar];B[ii];W[hi];B[as];W[gf];B[ge];W[ar];B[qg];W[bq];B[rg];W[pk];B[ok];W[ap];B[rd];W[ki];B[jh];W[sc];B[eg];W[eh];B[kr];W[jq];B[jr];W[ip];B[hr];W[mi];B[mj];W[li];B[mh];W[rh];B[lr];W[ns];B[mr];W[mq];B[sh];W[sf];B[se];W[sd];B[re];W[si];B[sg];W[ee];B[ef];W[os];B[ps];W[nj];B[nk];W[ni];B[nh];W[ig];B[qk];W[rj];B[ah];W[ag];B[if];W[jg];B[kg];W[ms];B[ls];W[ai];B[ds];W[fp];B[jp];W[ci];B[cj];W[ip];B[pb];W[qb];B[jp];W[cs];B[es];W[ip];B[qa];W[ra];B[jp];W[kq];B[ip];W[sq];B[sr];W[sp];B[go];W[fo];B[pk];W[ae];B[fl];W[jm];B[aj];W[ah];B[];W[])"
	Scoring2          = "(;RE[W+5.5]BR[1p]PB[Black]WR[1p]KM[6.5]PW[White];B[qd];W[cp];B[pp];W[dc];B[eq];W[oc];B[ce];W[qq];B[qp];W[pq];B[nq];W[oq];B[op];W[nr];B[rq];W[rr];B[do];W[dq];B[er];W[bn];B[or];W[pr];B[mr];W[fo];B[ns];W[rp];B[dp];W[cq];B[dm];W[ep];B[hq];W[ho];B[gn];W[fn];B[go];W[gp];B[hp];W[gm];B[hn];W[ek];B[gq];W[fp];B[cj];W[hl];B[hm];W[fl];B[il];W[hk];B[bm];W[cn];B[dh];W[pe];B[qe];W[pf];B[rg];W[mo];B[io];W[np];B[qn];W[pm];B[on];W[pn];B[mp];W[no];B[ro];W[sq];B[oo];W[lp];B[mq];W[lm];B[om];W[ko];B[kq];W[ok];B[ol];W[nk];B[pk];W[pj];B[qj];W[pi];B[qk];W[jd];B[cm];W[dn];B[em];W[fm];B[lk];W[kk];B[lj];W[kj];B[li];W[ll];B[ni];W[qg];B[rh];W[nl];B[ki];W[im];B[jm];W[jl];B[mf];W[md];B[og];W[pd];B[qc];W[qf];B[rf];W[lg];B[jj];W[ik];B[jg];W[mg];B[je];W[ke];B[ie];W[id];B[ge];W[he];B[hf];W[hd];B[gf];W[cd];B[be];W[de];B[df];W[gd];B[ee];W[dd];B[ob];W[nb];B[pc];W[nd];B[fd];W[fc];B[bd];W[bc];B[ph];W[qh];B[qi];W[oj];B[lf];W[kf];B[kg];W[nf];B[ng];W[le];B[mh];W[me];B[in];W[oh];B[dr];W[hh];B[ii];W[ih];B[hi];W[jh];B[kh];W[gh];B[gi];W[fh];B[fi];W[ji];B[ij];W[ei];B[eh];W[fj];B[fg];W[gj];B[di];W[ej];B[ig];W[jk];B[pa];W[am];B[al];W[an];B[bk];W[jp];B[jq];W[cr];B[na];W[mb];B[ma];W[la];B[oa];W[lb];B[ac];W[ab];B[ad];W[bb];B[cs];W[fq];B[fr];W[bs];B[ds];W[br];B[so];W[ps];B[kn];W[ln];B[ip];W[pg];B[nh];W[ed];B[fe];W[jo];B[jn];W[dl];B[cl];W[dk];B[ck];W[lq];B[lr];W[os];B[nr];W[jf];B[if];W[en];B[of];W[oe];B[sp];W[rq];B[nn];W[nj];B[km];W[il];B[lh];W[mj];B[oi];W[ph];B[gg];W[hj];B[dj];W[ml];B[nm];W[lo])"
	Scoring3          = "(;BR[2p]KM[6.5]PB[Black]PW[White]RE[W+0.5]WR[2p];B[pd];W[dd];B[pp];W[dp];B[cq];W[dq];B[cp];W[do];B[bn];W[nq];B[qn];W[pq];B[qq];W[qr];B[rq];W[op];B[pr];W[oq];B[rr];W[qc];B[pc];W[qd];B[pe];W[rf];B[jp];W[po];B[fc];W[hc];B[cc];W[dc];B[cd];W[de];B[db];W[eb];B[cb];W[fb];B[cf];W[kd];B[gq];W[cn];B[bm];W[iq];B[ip];W[hq];B[hp];W[gr];B[fq];W[cr];B[br];W[dr];B[co];W[fr];B[mc];W[eg];B[jq];W[jr];B[kr];W[ir];B[kb];W[jc];B[lq];W[om];B[lm];W[qp];B[rp];W[lo];B[jm];W[jh];B[le];W[go];B[qb];W[rb];B[pb];W[qg];B[qk];W[qo];B[rn];W[mm];B[ml];W[mn];B[ik];W[ke];B[hh];W[hi];B[fh];W[ii];B[fg];W[cg];B[ce];W[df];B[fj];W[hk];B[hl];W[gk];B[cj];W[di];B[dj];W[bf];B[be];W[il];B[jl];W[ei];B[gj];W[ej];B[fk];W[gl];B[im];W[ek];B[fl];W[gm];B[el];W[hn];B[en];W[gp];B[or];W[dk];B[ck];W[kp];B[jo];W[kq];B[mr];W[nr];B[ns];W[ks];B[fe];W[gc];B[jb];W[ib];B[lf];W[kk];B[fn];W[hj];B[lk];W[kj];B[ln];W[mi];B[ok];W[nf];B[ld];W[kc];B[lc];W[qi];B[id];W[ie];B[he];W[hd];B[je];W[if];B[jf];W[hf];B[kf];W[ge];B[eh];W[ci];B[dl];W[bh];B[ef];W[dg];B[qj];W[pi];B[ra];W[kl];B[ll];W[ae];B[ad];W[af];B[ab];W[bj];B[bk];W[rc];B[lr];W[lp];B[mo];W[mp];B[on];W[nm];B[pn];W[oo];B[ms];W[in];B[jn];W[nk];B[nl];W[pl];B[ol];W[pm];B[ql];W[bs];B[ar];W[of];B[gn];W[fp];B[hm];W[nd];B[fd];W[ec];B[mg];W[nh];B[lh];W[rj];B[rk];W[ri];B[aj];W[bi];B[dn];W[ja];B[lb];W[ro];B[so];W[ho];B[hg];W[gf];B[ki];W[ig];B[lj];W[ih];B[ff];W[jj];B[oi];W[oh];B[qe];W[re];B[od];W[ne];B[nc];W[mj];B[nj];W[mk];B[sk];W[qm];B[rm];W[no];B[pk];W[ai];B[ak];W[fm];B[ka];W[ia];B[ng];W[og];B[sj];W[si];B[ea];W[fa];B[da];W[em];B[dm];W[ic];B[jd];W[kg];B[pf];W[pg];B[nn];W[mo];B[sb];W[sc];B[qa];W[jk];B[dh];W[gd];B[km];W[ko];B[eo];W[ep];B[sa];W[ij];B[il];W[li];B[kh];W[jg];B[lg];W[ni];B[oj];W[qf];B[fi];W[gg];B[gh];W[ch];B[bq];W[js];B[qs];W[cs];B[os];W[mq];B[io];W[ed];B[kn];W[oe];B[fo];W[ee];B[ls];W[md];B[gi];W[me];B[as];W[mf];B[mh];W[ji];B[pj])"
	PassWithTT        = "(;PB[Black]PW[White]KM[7.5]RE[B+1.5];B[qd];W[dd];B[pp];W[dp];B[od];W[nq];B[lq];W[qn];B[np];W[fc];B[ql];W[mp];B[mq];W[qp];B[qq];W[op];B[no];W[po];B[pq];W[oo];B[oq];W[nn];B[mo];W[mn];B[lo];W[ln];B[ko];W[pk];B[qj];W[qk];B[rk];W[rl];B[rm];W[rj];B[sl];W[qi];B[pl];W[pj];B[nl];W[ll];B[mk];W[qf];B[lk];W[jl];B[jj];W[in];B[gd];W[mc];B[of];W[mi];B[kc];W[me];B[mg];W[ke];B[ld];W[md];B[le];W[lf];B[mf];W[lg];B[lh];W[mh];B[oh];W[jf];B[ic];W[ki];B[jm];W[im];B[kj];W[kh];B[jn];W[km];B[kl];W[kk];B[jk];W[il];B[kl];W[rq];B[rp];W[ro];B[qo];W[pe];B[oe];W[qp];B[sp];W[kk];B[qo];W[jo];B[kn];W[kl];B[on];W[jb];B[kd];W[kb];B[je];W[if];B[nb];W[mb];B[gc];W[fb];B[fd];W[ed];B[ff];W[df];B[kf];W[kg];B[fh];W[hi];B[lj];W[li];B[fj];W[gj];B[ok];W[oj];B[nj];W[gg];B[fg];W[ni];B[oi];W[pi];B[pf];W[qg];B[ch];W[pc];B[oc];W[pb];B[pd];W[ob];B[nc];W[na];B[rb];W[ga];B[re];W[rf];B[pg];W[cj];B[fk];W[om];B[pn];W[ol];B[nm];W[nk];B[hb];W[ha];B[ok];W[qe];B[rd];W[nk];B[lm];W[cm];B[dq];W[cq];B[eq];W[cr];B[dn];W[cn];B[do];W[ep];B[co];W[cp];B[bo];W[el];B[fn];W[fl];B[go];W[gq];B[hq];W[gp];B[ho];W[hp];B[io];W[iq];B[gk];W[gm];B[dk];W[ek];B[dj];W[ej];B[ei];W[ck];B[di];W[dl];B[jq];W[hk];B[gl];W[fm];B[gi];W[hj];B[hh];W[ih];B[ce];W[cf];B[bf];W[bd];B[be];W[cd];B[hg];W[hf];B[gf];W[ng];B[nf];W[ra];B[nh];W[ml];B[ok];W[ip];B[jp];W[nk];B[ia];W[ib];B[ok];W[ph];B[og];W[nk];B[gb];W[ja];B[ok];W[sf];B[nk];W[ig];B[gh];W[mm];B[ir];W[hr];B[de];W[ee];B[ef];W[jc];B[ie];W[qb];B[sb];W[bp];B[rh];W[ri];B[bg];W[bi];B[am];W[hl];B[fi];W[jr];B[kr];W[is];B[ji];W[jh];B[ad];W[ac];B[ae];W[bc];B[ak];W[bh];B[fo];W[id];B[hn];W[hm];B[ao];W[ii];B[he];W[se];B[sd];W[ag];B[ap];W[aq];B[fp];W[fq];B[ks];W[sj];B[js];W[ir];B[lc];W[lb];B[hc];W[jd];B[ke];W[sk];B[rl];W[oa];B[qa];W[qc];B[rc];W[pa];B[ma];W[la];B[sa];W[ma];B[qa];W[aj];B[bk];W[bm];B[al];W[bj];B[dm];W[ra];B[eo];W[em];B[qa];W[cl];B[cg];W[ra];B[ah];W[ai];B[af];W[qa];B[ah];W[ci];B[hd];W[ag];B[ar];W[bq];B[ah];W[fe];B[ge];W[ag];B[dr];W[er];B[ah];W[ij];B[ne];W[ag];B[db];W[ec];B[ah];W[ik];B[pm];W[ag];B[bb];W[cb];B[ah];W[mj];B[an];W[ag];B[ca];W[cc];B[ah];W[dg];B[dh];W[ag];B[ds];W[cs];B[ah];W[bl];B[nd];W[ag];B[ea];W[fa];B[ah];W[en];B[jo];W[ag];B[ba];W[ab];B[ah];W[bn];B[gn];W[ag];B[qh];W[sh];B[ah];W[tt];B[ag])"
	ChineseNames      = "(;GM[1]FF[4]SZ[19]GN[]DT[2020-01-01]PB[李晨宇]PW[王思雅]BR[9段]WR[9段]KM[375]HA[0]RU[Chinese]AP[GNU Go:3.8]RN[3]RE[B+R]TM[1200]TC[3]TT[60]AP[foxwq]RL[0];B[pd];W[dp];B[pq];W[dd];B[qo];W[nc];B[lc];W[qc];B[pc];W[qd];B[pe];W[pb];B[ob];W[qb];B[nb];W[qf];B[fq];W[cn];B[dq];W[cq])"
	MixedCaseField    = "(;GM[1]CoPyright[SomeCopyright]RE[W+Resign]PW[White]WR[1d]PB[Black]BR[1d]SZ[19]TM[60]KM[6.5];W[ed]WL[59];B[cd]BL[54];W[df]WL[57];B[dc]BL[42])"
	Handicap1         = "(;GM[1]FF[4]CA[UTF-8]ST[2]RU[Japanese]SZ[19]HA[4]KM[6.50]PW[White]PB[Black]AB[dd][pd][dp][pp];W[hm];B[jk];W[li];B[lf];W[gi];B[ig];W[dl];B[dj];W[eg];B[hd])"
	Resignation1      = "(;BR[4p]KM[6.5]PB[Black]PW[White]RE[B+R]WR[4p];B[pd];W[dp];B[pp];W[dd];B[fq];W[qq];B[pq];W[qp];B[po];W[rn];B[cf];W[cn];B[fc];W[df];B[dg];W[ef];B[cd];W[cc];B[ce];W[dc];B[hc];W[id];B[ic];W[jd];B[ge];W[jc];B[hf];W[fd];B[eb];W[eg];B[dh];W[gg];B[mc];W[cj];B[dj];W[dk];B[ej];W[ci];B[eh];W[de];B[jf];W[he];B[gd];W[gf];B[hd];W[ie];B[if];W[ld];B[lc];W[jb];B[gb];W[md];B[nc];W[mf];B[bh];W[gi];B[lf];W[mg];B[lg];W[lh];B[hh];W[gh];B[kh];W[ki];B[mh];W[li];B[me];W[le];B[ne];W[ng];B[kf];W[je];B[ke];W[kd];B[ji];W[ch];B[cg];W[jj];B[ii];W[ij];B[hi];W[hj];B[jg];W[bi];B[ck];W[bk];B[ag];W[lq];B[gj];W[gk];B[fj];W[fe];B[cl];W[dl];B[iq];W[lo];B[qn];W[rm];B[pl];W[qr];B[pj];W[pi];B[oj];W[nd];B[oe];W[od];B[pc];W[pe];B[pf];W[qe];B[of];W[oc];B[ob];W[pb];B[qb];W[pa];B[qa];W[qc];B[oa];W[pb];B[pa];W[qd];B[pb];W[lb];B[ma];W[ib];B[hb];W[qf];B[oh];W[ph];B[og];W[mb];B[nb];W[kb];B[rc];W[rd];B[rb];W[oi];B[ni];W[pg];B[qi];W[rh];B[ri];W[qh];B[sc];W[nj];B[nh];W[nk];B[nl];W[ml];B[nm];W[mm];B[ok];W[nn];B[on];W[eq];B[fr];W[om];B[ol];W[jr];B[jq];W[ir];B[hr];W[kq];B[is];W[kr];B[fo];W[cm];B[bc];W[bb];B[fm];W[gn];B[fn];W[fk];B[ac];W[ep];B[go];W[ab];B[ae];W[bd];B[ad];W[bf];B[be];W[io];B[in];W[jo];B[er];W[dr];B[ek];W[el];B[hn];W[hm];B[gm];W[ho];B[hl];W[im];B[cr];W[ds];B[do];W[cp];B[co];W[bp];B[jn];W[il];B[ln];W[mn];B[ko];W[kp];B[kn];W[kl];B[mo];W[no];B[mp];W[nq];B[np];W[lp];B[hp];W[jp];B[oo];W[pr];B[hk];W[fl];B[gl];W[mq];B[bo];W[br];B[es];W[fp];B[gp];W[gs];B[cs];W[dq];B[ap];W[bq];B[kj];W[ik];B[lk];W[mi];B[nf];W[ll];B[op];W[mk];B[mj];W[jl];B[kk];W[pm];B[qm])"
	MissingSZ         = "(;PB[Black]BR[3p]PW[White]WR[1p]KM[6.5]RE[W+R];B[pd];W[dp];B[pp];W[dc];B[de];W[ce];B[cf];W[cd];B[dg];W[fc];B[cn];W[fq];B[cp];W[cq];B[bq];W[co];B[bp];W[do];B[bo];W[cr];B[dn];W[ck];B[gp];W[gq];B[hp];W[ir])"
	Suicide1          = "(;GM[1]FF[4]CA[UTF-8]ST[2]RU[NZ]SZ[19]KM[6.50]PW[white]PB[black];B[cs];W[br];B[cr];W[bq];B[cq];W[bs];B[bp];W[aq];B[cp];W[ar];B[ap];W[as];B[ar])"
	TwoFalseEyes      = "(;CA[UTF-8]FF[4]GM[1]KM[6.5]PB[Black]PW[White]RU[Japanese]SZ[9];B[ah];B[bh];B[bi];B[ch];B[dh];B[di];B[eh];B[dg];B[ef];B[ff];B[fg];B[fe];B[gf];B[he];B[hd];B[gd];W[ag];W[bg];W[cg];W[cf];W[df];W[de];W[ee];W[ed];W[fd];W[fc];W[gc];W[hc];W[ic];W[if];W[hf];W[hg];W[gg];W[gh];W[fh];W[fi];W[ei])"
	AtariDame1        = "(;CA[UTF-8]FF[4]GM[1]KM[6.5]PB[Black]PW[White]RU[Japanese]SZ[9];B[ah];B[bh];B[bi];B[ch];B[dh];B[di];B[dg];B[ef];B[ff];B[eh];B[fh];B[gf];B[gg];W[ag];W[bg];W[cg];W[cf];W[df];W[de];W[ee];W[fe];W[ge];W[he];W[hf];W[hh];W[gh];W[gi];W[fi];W[ei];W[fg];W[if];W[ig];W[ih])"
	AtariDame2        = "(;CA[UTF-8]FF[4]GM[1]KM[6.5]PB[Black]PW[White]RU[Japanese]SZ[9];W[bh];W[ch];W[dh];B[di];B[ci];B[bi];B[ah];B[bg];B[cg];B[cf];B[ce];B[be];B[ae];B[cd];B[cc];B[cb];B[ca];W[da];W[db];W[dc];W[dd];W[de];W[df];W[dg];W[eh];W[fh];W[fi])"
)

var SimpleZip = []byte{80, 75, 3, 4, 20, 0, 0, 0, 8, 0, 247, 179, 103, 91, 97, 146, 135, 115, 97, 0, 0, 0, 106, 0, 0, 0, 7, 0, 28, 0, 102, 111, 111, 46, 115, 103, 102, 85, 84, 9, 0, 3, 193, 213, 14, 105, 195, 213, 14, 105, 117, 120, 11, 0, 1, 4, 232, 3, 0, 0, 4, 232, 3, 0, 0, 211, 176, 14, 8, 143, 14, 207, 200, 44, 73, 141, 13, 10, 141, 246, 74, 44, 72, 204, 75, 45, 78, 141, 245, 246, 141, 54, 211, 51, 141, 117, 247, 141, 54, 140, 117, 115, 139, 54, 137, 117, 118, 140, 14, 13, 113, 211, 181, 136, 13, 142, 138, 54, 180, 140, 13, 112, 138, 118, 202, 73, 76, 206, 142, 213, 176, 118, 138, 46, 72, 137, 181, 14, 143, 78, 1, 146, 64, 118, 1, 152, 93, 16, 171, 9, 146, 73, 1, 203, 164, 166, 198, 106, 106, 114, 1, 0, 80, 75, 1, 2, 30, 3, 20, 0, 0, 0, 8, 0, 247, 179, 103, 91, 97, 146, 135, 115, 97, 0, 0, 0, 106, 0, 0, 0, 7, 0, 24, 0, 0, 0, 0, 0, 1, 0, 0, 0, 164, 129, 0, 0, 0, 0, 102, 111, 111, 46, 115, 103, 102, 85, 84, 5, 0, 3, 193, 213, 14, 105, 117, 120, 11, 0, 1, 4, 232, 3, 0, 0, 4, 232, 3, 0, 0, 80, 75, 5, 6, 0, 0, 0, 0, 1, 0, 1, 0, 77, 0, 0, 0, 162, 0, 0, 0, 0, 0}
